
spring:
  application:
    name: config-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1-server.com:5001/eureka, http://eureka-2-server.com:5002/eureka, http://eureka-3-server.com:5003/eureka
